### ISSUE TITLE
ConfigLoader->OmniaConfigLoader

### ISSUE THREAD

**Issue by imlercj** [takikadiri/kedro-boot#12]
Hi, I am building a pipeline to use with Kedro-boot, but get this error:

```
ImportError: cannot import name 'ConfigLoader' from 'kedro.config' (/opt/homebrew/Caskroom/miniforge/base/envs/cogniteds/lib/python3.11/site-packages/kedro/config/__init__.py)
Traceback (most recent call last):
```

According to the new release note, ConfigLoader has been replaced with OmniaConfigLoader, are you planning to release a new version.

**Comment by takikadiri** [comment]
Hi, thank you for raising this. kedro-boot will natively support OmegaConfigLoader [with the support of kedro 0.19.x](https://github.com/takikadiri/kedro-boot/issues/9)

**Comment by takikadiri** [comment]
@imlercj The kedro-boot support of kedro > 0.19.x is merged, it subquesently support OmegaConfigLoader. Moreover, the support of the `boot_package` is also merged. 

Could you please test you [discussed use cases](https://kedro-org.slack.com/archives/C03RKP2LW64/p1706187566260409) against the main branch of kedro-boot ? 
Since you inject data into the session, you would need declaring you're inputs in compilation_specs like follow : 
```python
from kedro_boot.app.booter import boot_package
from kedro_boot.framework.compilation.specs import CompilationSpec
session = boot_package(package_name="<your_package>", compilation_specs=[CompilationSpec(inputs=["your_client_dataset_name"])], kedro_args={"pipeline": "your_pipeline", conf_source="<your_conf_source>", ....})
run_resultst = session.run(inputs={"your_client_dataset_name": your_client})
```
