### ISSUE TITLE
Add more information to examples

### ISSUE THREAD

**Issue by erickfigueiredo** [takikadiri/kedro-boot#34]
Hi,

Could you please provide more detailed examples, especially regarding FastAPI? I’m particularly interested in running my app using the Uvicorn approach. The current example lacks the extra steps and commands necessary for executing the application. I would like to know how to change parameters like workers and timeout, which are only accessible via Uvicorn.

Thank you for your assistance!

**Comment by takikadiri** [comment]
Hi,
Thank you for pointing to this. The project and example README files currently don't demonstrate a complete example of running a FastAPI app in standalone mode (with Uvicorn, for example). I'll work on including such an example and adding proper documentation for the plugin.

Since your app is a [standalone app](https://github.com/takikadiri/kedro-boot/tree/80939643d6ade11c5df06c2f5b6e1b66f57e7aaa?tab=readme-ov-file#use-case-1--the-standalone-mode---how-to-run-a-kedro-pipeline-from-another-application), which means it holds the entry point (Uvicorn here), you have complete control over the Uvicorn configuration. There are no dependencies with kedro or kedro-boot CLI/configs.

The only thing you need to do is create a `kedro_boot_session` in your app using `boot_project` or `boot_package`, so you can access your Kedro pipelines. You can also use a Kedro config_loader if you'd like to make it the config loader for your app, although this is optional.

You can refer to the [Streamlit example](https://github.com/takikadiri/kedro-boot/blob/80939643d6ade11c5df06c2f5b6e1b66f57e7aaa/examples/src/spaceflights_streamlit/app.py). It explicitly creates a `kedro_boot_session` because it's a standalone app like yours.

Let me know if this works for you, and feel free to ask if you need further assistance.

**Comment by erickfigueiredo** [comment]
Hi! Thank you for your assistance!

In my project, I have the following structure:

`pipeline_regsitry.py`
```python

...
def register_dynamic_pipelines(catalog: DataCatalog):
	...  
	  
	example_api_pipeline = pipeline(example_pipeline.nodes,  
	                               namespace = 'example_api',  
	                               inputs = {...},  
	                               parameters = {...}  
	                               )  
def register_pipelines():  
    pipelines["__default__"] = example_api_pipeline    
    return pipelines  
  
return register_pipelines
```
`api.py`
``` python
...
app = FastAPI(title='My API', version='0.1.0')  
  
app.add_middleware(  
    CORSMiddleware,  
    allow_origins=['*'],  
    allow_methods=["*"],  
    allow_headers=["*"],  
    allow_credentials=True  
)  
  
  
@app.post('/init', tags=['example_api'], operation_id='example_api')  
def responses(history: History, kedro_run: KedroFastApi):  
    response = kedro_run.get('example_api.responses', [])  
    return response[0] if len(response) else {}  
  
  
@app.get('/')  
async def docs_redirect():  
    return RedirectResponse(url='/docs')
    
```

### My current setup

At the moment, I'm calling FastAPI using the following command:
`kedro boot fastapi --app example_api.api.app --port 8081`

### Question

How could I change the implementation to run FastAPI directly with uvicorn, and how should I invoke it from the terminal?

**Comment by takikadiri** [comment]
You need to basically create and use a `kedro_boot_session` in your app. In this way, your app is no more managed by kedro, contrary to your precedent approach (kedro boot fastapi). You can code explicitely your entry point logic. Here is an example:

```python
import uvicorn
from pathlib import Path
from fastapi import FastAPI
from kedro_boot.app.booter import boot_project

# Create and configure FastApi App
app = FastAPI(title='My API', version='0.1.0')  
  
app.add_middleware(  
    CORSMiddleware,  
    allow_origins=['*'],  
    allow_methods=["*"],  
    allow_headers=["*"],  
    allow_credentials=True  
)  

# Create Kedro Boot Session
kedro_boot_session = boot_project(project_path=Path.cwd(), kedro_args={"pipeline": "__default__"})

# Configure FastApi app endpoints
@app.post('/init', tags=['example_api']) 
def responses(history: History):  
    response = kedro_boot_session.run(
            namespace="example_api", inputs={"history": history}
        )
    # Some potential last mile formating ...
    return response

@app.get('/')  
async def docs_redirect():  
    return RedirectResponse(url='/docs')
```

Run your app with uvicorn
`uvicorn  example_api.api:app --port 8081`

Note that there is no more need of `kedro_run: KedroFastApi` or `operation_id` in the route attributes as there is no FastApi <--> Kedro object mapping in this mode (Standalone app)

Let me know if it works for you

**Comment by erickfigueiredo** [comment]
Works perfectly! Thank you @takikadiri for your dedication to this issue 😁
